@startuml

!include ../common.plantuml!0

class Vector2{

    + new(x:number, y:number)

    + norm(): number
    + toString(): string
    + dot(vec:Vector2): number
    + cross(vec:Vector2): Vector2
    + __add(): Vector2
    + __sub(): Vector2
    + __div(): Vector2
    + __mul(): Vector2
}

class Vector3{

    + new(x:number, y:number, z:number)

    + norm(): number
    + toString(): string
    + dot(vec:Vector3): number
    + cross(vec:Vector3): Vector3
    + __add(): Vector3
    + __sub(): Vector3
    + __mul(): Vector3
    + __div(): Vector3
}


@enduml