---@class AdvancedPeripherals.PlayerDetector
---@field getPlayersInRange fun(range:number):table<number,string>
---@field getOnlinePlayers fun():table<number,string>
---@field getPlayerPos fun(player:string):AdvancedPeripherals.PlayerDetector.PlayerInfo
--
--
---@class AdvancedPeripherals.PlayerDetector.PlayerInfo
---@field dimension string dimension where player is
---@field eyeHeight number height of player
---@field pitch number player head pitch, up is -90, down is 90
---@field yaw number player heading, when north is 0
---@field x number player position x
---@field y number player position y
---@field z number player position z
