@startuml

!include ../common.plantuml!0

enum Events
class Router{

    + new()

    + attachEventCallback(event:EventRouter.Events, mthd: func): void
    + attachRednetCallback(protocol:string, mthd:func): void
    + detachEventCallback(event:EventRouter.Events, mthd:func): void
    + removeEventCallback(event:EventRouter.Events): void
    + detachRednetCallback(protocol:string, mthd:func): void
    + removeRednetEventCallBack(protocol:string): void
    + attachUIRunner(UIrunner:UIRunner): void
    + main(): void

    - _runCallbacks(functionTable:table<number, func>, a:string, b:string, c:string, d:string): void
    - _eventCallbacks: table<EventRouter.Events, table<number,\n func>
    - _rednetCallbacks: table<string, table<number,\n func>
}


@enduml